### ISSUE TITLE
No repositories found for organization cisc3410 @rivlev

### ISSUE THREAD

**Issue by irinafedorovacisc** [cisc3410/docs#2]
Can someone tell me how to fix "**No repositories found for organization
cisc3410**" on Travis issue, I know this question previously came up in Issues, but I cant find it.

**Comment by XavMa** [comment]
Here's a reference  https://github.com/cisc3130/2-list/issues/2

**Comment by irinafedorovacisc** [comment]
@XavMa  Thank you very much, you saved me so much time
